"""
config.py — Bordeaux Spray Advisor
Crop profiles, all-India districts, agronomic constants.
Expert attribution: Dr. Prashant Raysad, Agriculturist
"""

# ── AGRONOMIC CONSTANTS ─────────────────────────────────────────────
RAIN_THRESHOLD_MM = 40 * 25.4   # 40 inches = 1016 mm
DAY_THRESHOLD     = 45           # days before mandatory re-spray
FORECAST_DAYS     = 15           # 15-day prediction window
RAIN_SAFE_MM      = 2.0          # mm threshold — below this = rain-free

EXPERT = {
    "name":        "Dr. Prashant Raysad",
    "designation": "Agriculturist",          # changed from Agronomist
    "org":         "Dhi Insights",
}

# ── CROP PROFILES ───────────────────────────────────────────────────
CROPS = {
    "areca": {
        "label":    "Areca Nut",
        "emoji":    "🌴",
        "disease":  "Koleroga (Fruit Rot) / Mahali",
        "bm_pct":   1.0,
        "bm_ratio": "1:1:100",
        "notes":    "Critical pre-monsoon window. First spray before first rains.",
    },
    "pepper": {
        "label":    "Black Pepper",
        "emoji":    "🫑",
        "disease":  "Phytophthora foot rot / Slow decline",
        "bm_pct":   1.0,
        "bm_ratio": "1:1:100",
        "notes":    "Apply to stem base and lower runners. Avoid midday heat.",
    },
    "cardamom": {
        "label":    "Cardamom",
        "emoji":    "🌿",
        "disease":  "Capsule rot / Rhizome rot",
        "bm_pct":   0.5,
        "bm_ratio": "0.5:0.5:100",
        "notes":    "Use lower concentration — crop is sensitive to copper excess.",
    },
    "coffee": {
        "label":    "Coffee",
        "emoji":    "☕",
        "disease":  "Coffee Berry Disease / Leaf rust",
        "bm_pct":   1.0,
        "bm_ratio": "1:1:100",
        "notes":    "Cover underside of leaves. Spray at blossom shower onset.",
    },
}

# ── ALL-INDIA DISTRICTS ─────────────────────────────────────────────
# Format: key → {state, lat, lon, pin_prefix, display}
# 750+ major districts across all 28 states + 8 UTs
# Grouped by state for UI display

DISTRICTS = {
    # ── ANDHRA PRADESH ──
    "srikakulam":         {"state":"Andhra Pradesh",  "lat":18.30, "lon":83.90, "display":"Srikakulam"},
    "vizianagaram":       {"state":"Andhra Pradesh",  "lat":18.12, "lon":83.42, "display":"Vizianagaram"},
    "visakhapatnam":      {"state":"Andhra Pradesh",  "lat":17.72, "lon":83.30, "display":"Visakhapatnam"},
    "east_godavari":      {"state":"Andhra Pradesh",  "lat":17.00, "lon":82.00, "display":"East Godavari"},
    "west_godavari":      {"state":"Andhra Pradesh",  "lat":16.92, "lon":81.33, "display":"West Godavari"},
    "krishna":            {"state":"Andhra Pradesh",  "lat":16.52, "lon":80.62, "display":"Krishna"},
    "guntur":             {"state":"Andhra Pradesh",  "lat":16.30, "lon":80.44, "display":"Guntur"},
    "prakasam":           {"state":"Andhra Pradesh",  "lat":15.33, "lon":79.57, "display":"Prakasam"},
    "nellore":            {"state":"Andhra Pradesh",  "lat":14.44, "lon":79.99, "display":"Nellore (SPSR)"},
    "kurnool":            {"state":"Andhra Pradesh",  "lat":15.83, "lon":78.04, "display":"Kurnool"},
    "kadapa":             {"state":"Andhra Pradesh",  "lat":14.47, "lon":78.82, "display":"YSR Kadapa"},
    "anantapur":          {"state":"Andhra Pradesh",  "lat":14.68, "lon":77.60, "display":"Anantapur"},
    "chittoor":           {"state":"Andhra Pradesh",  "lat":13.22, "lon":79.10, "display":"Chittoor"},
    # ── ARUNACHAL PRADESH ──
    "tawang":             {"state":"Arunachal Pradesh","lat":27.59, "lon":91.86, "display":"Tawang"},
    "west_kameng":        {"state":"Arunachal Pradesh","lat":27.03, "lon":92.57, "display":"West Kameng"},
    "east_kameng":        {"state":"Arunachal Pradesh","lat":27.33, "lon":93.25, "display":"East Kameng"},
    "papum_pare":         {"state":"Arunachal Pradesh","lat":27.10, "lon":93.60, "display":"Papum Pare"},
    "upper_subansiri":    {"state":"Arunachal Pradesh","lat":27.67, "lon":94.00, "display":"Upper Subansiri"},
    "lower_subansiri":    {"state":"Arunachal Pradesh","lat":27.27, "lon":93.83, "display":"Lower Subansiri"},
    "west_siang":         {"state":"Arunachal Pradesh","lat":28.14, "lon":94.70, "display":"West Siang"},
    "east_siang":         {"state":"Arunachal Pradesh","lat":28.02, "lon":95.30, "display":"East Siang"},
    "upper_siang":        {"state":"Arunachal Pradesh","lat":29.00, "lon":95.50, "display":"Upper Siang"},
    "lohit":              {"state":"Arunachal Pradesh","lat":27.83, "lon":96.17, "display":"Lohit"},
    "changlang":          {"state":"Arunachal Pradesh","lat":27.12, "lon":96.42, "display":"Changlang"},
    "tirap":              {"state":"Arunachal Pradesh","lat":27.07, "lon":95.73, "display":"Tirap"},
    # ── ASSAM ──
    "kamrup_metro":       {"state":"Assam",           "lat":26.14, "lon":91.74, "display":"Kamrup (Metro) / Guwahati"},
    "kamrup":             {"state":"Assam",           "lat":26.28, "lon":91.29, "display":"Kamrup"},
    "sonitpur":           {"state":"Assam",           "lat":26.60, "lon":92.80, "display":"Sonitpur"},
    "dibrugarh":          {"state":"Assam",           "lat":27.49, "lon":94.91, "display":"Dibrugarh"},
    "jorhat":             {"state":"Assam",           "lat":26.75, "lon":94.21, "display":"Jorhat"},
    "sibsagar":           {"state":"Assam",           "lat":26.98, "lon":94.64, "display":"Sivasagar"},
    "nagaon":             {"state":"Assam",           "lat":26.35, "lon":92.68, "display":"Nagaon"},
    "morigaon":           {"state":"Assam",           "lat":26.25, "lon":92.33, "display":"Morigaon"},
    "cachar":             {"state":"Assam",           "lat":24.80, "lon":92.86, "display":"Cachar"},
    "barpeta":            {"state":"Assam",           "lat":26.32, "lon":91.00, "display":"Barpeta"},
    "dhubri":             {"state":"Assam",           "lat":26.02, "lon":89.99, "display":"Dhubri"},
    "goalpara":           {"state":"Assam",           "lat":26.17, "lon":90.62, "display":"Goalpara"},
    "kokrajhar":          {"state":"Assam",           "lat":26.40, "lon":90.27, "display":"Kokrajhar"},
    "lakhimpur":          {"state":"Assam",           "lat":27.23, "lon":94.10, "display":"Lakhimpur"},
    "tinsukia":           {"state":"Assam",           "lat":27.49, "lon":95.36, "display":"Tinsukia"},
    "golaghat":           {"state":"Assam",           "lat":26.52, "lon":93.97, "display":"Golaghat"},
    # ── BIHAR ──
    "patna":              {"state":"Bihar",           "lat":25.61, "lon":85.14, "display":"Patna"},
    "gaya":               {"state":"Bihar",           "lat":24.80, "lon":85.00, "display":"Gaya"},
    "muzaffarpur":        {"state":"Bihar",           "lat":26.12, "lon":85.36, "display":"Muzaffarpur"},
    "bhagalpur":          {"state":"Bihar",           "lat":25.25, "lon":86.98, "display":"Bhagalpur"},
    "darbhanga":          {"state":"Bihar",           "lat":26.17, "lon":85.90, "display":"Darbhanga"},
    "purnia":             {"state":"Bihar",           "lat":25.78, "lon":87.47, "display":"Purnia"},
    "nalanda":            {"state":"Bihar",           "lat":25.13, "lon":85.44, "display":"Nalanda"},
    "begusarai":          {"state":"Bihar",           "lat":25.42, "lon":86.13, "display":"Begusarai"},
    "samastipur":         {"state":"Bihar",           "lat":25.87, "lon":85.78, "display":"Samastipur"},
    "saran":              {"state":"Bihar",           "lat":25.92, "lon":84.75, "display":"Saran"},
    "vaishali":           {"state":"Bihar",           "lat":25.68, "lon":85.21, "display":"Vaishali"},
    "sitamarhi":          {"state":"Bihar",           "lat":26.60, "lon":85.49, "display":"Sitamarhi"},
    "madhubani":          {"state":"Bihar",           "lat":26.36, "lon":86.07, "display":"Madhubani"},
    "bhojpur":            {"state":"Bihar",           "lat":25.55, "lon":84.47, "display":"Bhojpur"},
    "rohtas":             {"state":"Bihar",           "lat":24.99, "lon":84.04, "display":"Rohtas"},
    "aurangabad_br":      {"state":"Bihar",           "lat":24.75, "lon":84.37, "display":"Aurangabad (Bihar)"},
    # ── CHHATTISGARH ──
    "raipur":             {"state":"Chhattisgarh",   "lat":21.25, "lon":81.63, "display":"Raipur"},
    "bilaspur_cg":        {"state":"Chhattisgarh",   "lat":22.09, "lon":82.14, "display":"Bilaspur"},
    "durg":               {"state":"Chhattisgarh",   "lat":21.19, "lon":81.28, "display":"Durg"},
    "rajnandgaon":        {"state":"Chhattisgarh",   "lat":21.10, "lon":81.03, "display":"Rajnandgaon"},
    "korba":              {"state":"Chhattisgarh",   "lat":22.35, "lon":82.69, "display":"Korba"},
    "raigarh_cg":         {"state":"Chhattisgarh",   "lat":21.90, "lon":83.40, "display":"Raigarh"},
    "surguja":            {"state":"Chhattisgarh",   "lat":23.12, "lon":83.20, "display":"Surguja"},
    "bastar":             {"state":"Chhattisgarh",   "lat":19.12, "lon":81.95, "display":"Bastar"},
    "jagdalpur":          {"state":"Chhattisgarh",   "lat":19.08, "lon":82.02, "display":"Jagdalpur"},
    "kanker":             {"state":"Chhattisgarh",   "lat":20.27, "lon":81.49, "display":"Kanker"},
    # ── GOA ──
    "north_goa":          {"state":"Goa",            "lat":15.55, "lon":73.97, "display":"North Goa (Panaji)"},
    "south_goa":          {"state":"Goa",            "lat":15.17, "lon":74.08, "display":"South Goa (Margao)"},
    # ── GUJARAT ──
    "ahmedabad":          {"state":"Gujarat",        "lat":23.03, "lon":72.58, "display":"Ahmedabad"},
    "surat":              {"state":"Gujarat",        "lat":21.17, "lon":72.83, "display":"Surat"},
    "vadodara":           {"state":"Gujarat",        "lat":22.31, "lon":73.18, "display":"Vadodara"},
    "rajkot":             {"state":"Gujarat",        "lat":22.30, "lon":70.80, "display":"Rajkot"},
    "gandhinagar":        {"state":"Gujarat",        "lat":23.22, "lon":72.68, "display":"Gandhinagar"},
    "bhavnagar":          {"state":"Gujarat",        "lat":21.77, "lon":72.15, "display":"Bhavnagar"},
    "jamnagar":           {"state":"Gujarat",        "lat":22.47, "lon":70.07, "display":"Jamnagar"},
    "junagadh":           {"state":"Gujarat",        "lat":21.52, "lon":70.46, "display":"Junagadh"},
    "kutch":              {"state":"Gujarat",        "lat":23.73, "lon":69.86, "display":"Kutch"},
    "anand":              {"state":"Gujarat",        "lat":22.56, "lon":72.95, "display":"Anand"},
    "mehsana":            {"state":"Gujarat",        "lat":23.60, "lon":72.38, "display":"Mehsana"},
    "patan":              {"state":"Gujarat",        "lat":23.85, "lon":72.13, "display":"Patan"},
    "sabarkantha":        {"state":"Gujarat",        "lat":23.60, "lon":73.02, "display":"Sabarkantha"},
    "banaskantha":        {"state":"Gujarat",        "lat":24.17, "lon":72.43, "display":"Banaskantha"},
    "navsari":            {"state":"Gujarat",        "lat":20.95, "lon":72.92, "display":"Navsari"},
    "valsad":             {"state":"Gujarat",        "lat":20.62, "lon":73.00, "display":"Valsad"},
    "bharuch":            {"state":"Gujarat",        "lat":21.70, "lon":73.00, "display":"Bharuch"},
    # ── HARYANA ──
    "gurugram":           {"state":"Haryana",        "lat":28.46, "lon":77.03, "display":"Gurugram"},
    "faridabad":          {"state":"Haryana",        "lat":28.41, "lon":77.31, "display":"Faridabad"},
    "ambala":             {"state":"Haryana",        "lat":30.38, "lon":76.78, "display":"Ambala"},
    "karnal":             {"state":"Haryana",        "lat":29.69, "lon":76.99, "display":"Karnal"},
    "hisar":              {"state":"Haryana",        "lat":29.16, "lon":75.72, "display":"Hisar"},
    "rohtak":             {"state":"Haryana",        "lat":28.90, "lon":76.57, "display":"Rohtak"},
    "panipat":            {"state":"Haryana",        "lat":29.39, "lon":76.97, "display":"Panipat"},
    "sonipat":            {"state":"Haryana",        "lat":28.99, "lon":77.02, "display":"Sonipat"},
    "sirsa":              {"state":"Haryana",        "lat":29.53, "lon":75.03, "display":"Sirsa"},
    "bhiwani":            {"state":"Haryana",        "lat":28.79, "lon":76.13, "display":"Bhiwani"},
    "yamunanagar":        {"state":"Haryana",        "lat":30.13, "lon":77.30, "display":"Yamunanagar"},
    "kurukshetra":        {"state":"Haryana",        "lat":29.97, "lon":76.88, "display":"Kurukshetra"},
    "rewari":             {"state":"Haryana",        "lat":28.20, "lon":76.62, "display":"Rewari"},
    "mahendragarh":       {"state":"Haryana",        "lat":28.27, "lon":76.15, "display":"Mahendragarh"},
    # ── HIMACHAL PRADESH ──
    "shimla":             {"state":"Himachal Pradesh","lat":31.10, "lon":77.17, "display":"Shimla"},
    "kangra":             {"state":"Himachal Pradesh","lat":32.10, "lon":76.27, "display":"Kangra"},
    "mandi_hp":           {"state":"Himachal Pradesh","lat":31.71, "lon":76.93, "display":"Mandi"},
    "kullu":              {"state":"Himachal Pradesh","lat":31.96, "lon":77.11, "display":"Kullu"},
    "solan":              {"state":"Himachal Pradesh","lat":30.91, "lon":77.10, "display":"Solan"},
    "sirmaur":            {"state":"Himachal Pradesh","lat":30.57, "lon":77.46, "display":"Sirmaur"},
    "hamirpur_hp":        {"state":"Himachal Pradesh","lat":31.69, "lon":76.52, "display":"Hamirpur (HP)"},
    "una":                {"state":"Himachal Pradesh","lat":31.47, "lon":76.27, "display":"Una"},
    "chamba":             {"state":"Himachal Pradesh","lat":32.57, "lon":76.13, "display":"Chamba"},
    "lahaul_spiti":       {"state":"Himachal Pradesh","lat":32.57, "lon":77.57, "display":"Lahaul & Spiti"},
    "kinnaur":            {"state":"Himachal Pradesh","lat":31.59, "lon":78.47, "display":"Kinnaur"},
    "bilaspur_hp":        {"state":"Himachal Pradesh","lat":31.34, "lon":76.76, "display":"Bilaspur (HP)"},
    # ── JHARKHAND ──
    "ranchi":             {"state":"Jharkhand",      "lat":23.35, "lon":85.33, "display":"Ranchi"},
    "dhanbad":            {"state":"Jharkhand",      "lat":23.80, "lon":86.45, "display":"Dhanbad"},
    "bokaro":             {"state":"Jharkhand",      "lat":23.67, "lon":85.98, "display":"Bokaro"},
    "east_singhbhum":     {"state":"Jharkhand",      "lat":22.81, "lon":86.19, "display":"East Singhbhum (Jamshedpur)"},
    "west_singhbhum":     {"state":"Jharkhand",      "lat":22.17, "lon":85.17, "display":"West Singhbhum"},
    "hazaribagh":         {"state":"Jharkhand",      "lat":23.99, "lon":85.36, "display":"Hazaribagh"},
    "giridih":            {"state":"Jharkhand",      "lat":24.19, "lon":86.30, "display":"Giridih"},
    "deoghar":            {"state":"Jharkhand",      "lat":24.49, "lon":86.70, "display":"Deoghar"},
    "dumka":              {"state":"Jharkhand",      "lat":24.27, "lon":87.25, "display":"Dumka"},
    "palamu":             {"state":"Jharkhand",      "lat":24.03, "lon":84.08, "display":"Palamu"},
    # ── KARNATAKA ──
    "bengaluru_urban":    {"state":"Karnataka",      "lat":12.97, "lon":77.60, "display":"Bengaluru Urban"},
    "bengaluru_rural":    {"state":"Karnataka",      "lat":13.22, "lon":77.49, "display":"Bengaluru Rural"},
    "mysuru":             {"state":"Karnataka",      "lat":12.30, "lon":76.65, "display":"Mysuru"},
    "mangaluru":          {"state":"Karnataka",      "lat":12.87, "lon":74.88, "display":"Dakshina Kannada (Mangaluru)"},
    "belagavi":           {"state":"Karnataka",      "lat":15.85, "lon":74.50, "display":"Belagavi"},
    "kalaburagi":         {"state":"Karnataka",      "lat":17.33, "lon":76.82, "display":"Kalaburagi"},
    "dharwad":            {"state":"Karnataka",      "lat":15.46, "lon":75.01, "display":"Dharwad"},
    "shivamogga":         {"state":"Karnataka",      "lat":13.93, "lon":75.57, "display":"Shivamogga"},
    "chikmagalur":        {"state":"Karnataka",      "lat":13.32, "lon":75.77, "display":"Chikkamagaluru"},
    "hassan":             {"state":"Karnataka",      "lat":13.00, "lon":76.10, "display":"Hassan"},
    "kodagu":             {"state":"Karnataka",      "lat":12.42, "lon":75.74, "display":"Kodagu (Coorg)"},
    "uttara_kannada":     {"state":"Karnataka",      "lat":14.79, "lon":74.69, "display":"Uttara Kannada"},
    "udupi":              {"state":"Karnataka",      "lat":13.34, "lon":74.75, "display":"Udupi"},
    "tumakuru":           {"state":"Karnataka",      "lat":13.34, "lon":77.10, "display":"Tumakuru"},
    "chitradurga":        {"state":"Karnataka",      "lat":14.23, "lon":76.40, "display":"Chitradurga"},
    "davanagere":         {"state":"Karnataka",      "lat":14.46, "lon":75.92, "display":"Davanagere"},
    "chikkaballapur":     {"state":"Karnataka",      "lat":13.44, "lon":77.73, "display":"Chikkaballapur"},
    "kolar":              {"state":"Karnataka",      "lat":13.14, "lon":78.13, "display":"Kolar"},
    "ramanagara":         {"state":"Karnataka",      "lat":12.72, "lon":77.28, "display":"Ramanagara"},
    "mandya":             {"state":"Karnataka",      "lat":12.52, "lon":76.90, "display":"Mandya"},
    "chamarajanagar":     {"state":"Karnataka",      "lat":11.92, "lon":76.94, "display":"Chamarajanagar"},
    "ballari":            {"state":"Karnataka",      "lat":15.14, "lon":76.93, "display":"Ballari"},
    "koppal":             {"state":"Karnataka",      "lat":15.36, "lon":76.15, "display":"Koppal"},
    "gadag":              {"state":"Karnataka",      "lat":15.43, "lon":75.63, "display":"Gadag"},
    "haveri":             {"state":"Karnataka",      "lat":14.79, "lon":75.40, "display":"Haveri"},
    "bagalkot":           {"state":"Karnataka",      "lat":16.18, "lon":75.70, "display":"Bagalkot"},
    "vijayapura":         {"state":"Karnataka",      "lat":16.83, "lon":75.72, "display":"Vijayapura (Bijapur)"},
    "bidar":              {"state":"Karnataka",      "lat":17.91, "lon":77.52, "display":"Bidar"},
    "raichur":            {"state":"Karnataka",      "lat":16.21, "lon":77.36, "display":"Raichur"},
    "yadgir":             {"state":"Karnataka",      "lat":16.77, "lon":77.14, "display":"Yadgir"},
    # ── KERALA ──
    "thiruvananthapuram": {"state":"Kerala",         "lat":8.52,  "lon":76.94, "display":"Thiruvananthapuram"},
    "kollam":             {"state":"Kerala",         "lat":8.89,  "lon":76.59, "display":"Kollam"},
    "pathanamthitta":     {"state":"Kerala",         "lat":9.27,  "lon":76.78, "display":"Pathanamthitta"},
    "alappuzha":          {"state":"Kerala",         "lat":9.49,  "lon":76.33, "display":"Alappuzha"},
    "kottayam":           {"state":"Kerala",         "lat":9.59,  "lon":76.52, "display":"Kottayam"},
    "idukki":             {"state":"Kerala",         "lat":9.85,  "lon":77.10, "display":"Idukki"},
    "ernakulam":          {"state":"Kerala",         "lat":9.98,  "lon":76.28, "display":"Ernakulam (Kochi)"},
    "thrissur":           {"state":"Kerala",         "lat":10.52, "lon":76.21, "display":"Thrissur"},
    "palakkad":           {"state":"Kerala",         "lat":10.78, "lon":76.65, "display":"Palakkad"},
    "malappuram":         {"state":"Kerala",         "lat":11.07, "lon":76.07, "display":"Malappuram"},
    "kozhikode":          {"state":"Kerala",         "lat":11.25, "lon":75.78, "display":"Kozhikode"},
    "wayanad":            {"state":"Kerala",         "lat":11.62, "lon":76.13, "display":"Wayanad"},
    "kannur":             {"state":"Kerala",         "lat":11.87, "lon":75.37, "display":"Kannur"},
    "kasaragod":          {"state":"Kerala",         "lat":12.50, "lon":74.99, "display":"Kasaragod"},
    # ── MADHYA PRADESH ──
    "bhopal":             {"state":"Madhya Pradesh", "lat":23.26, "lon":77.41, "display":"Bhopal"},
    "indore":             {"state":"Madhya Pradesh", "lat":22.72, "lon":75.86, "display":"Indore"},
    "jabalpur":           {"state":"Madhya Pradesh", "lat":23.18, "lon":79.95, "display":"Jabalpur"},
    "gwalior":            {"state":"Madhya Pradesh", "lat":26.22, "lon":78.18, "display":"Gwalior"},
    "ujjain":             {"state":"Madhya Pradesh", "lat":23.18, "lon":75.78, "display":"Ujjain"},
    "sagar_mp":           {"state":"Madhya Pradesh", "lat":23.84, "lon":78.73, "display":"Sagar"},
    "rewa":               {"state":"Madhya Pradesh", "lat":24.53, "lon":81.30, "display":"Rewa"},
    "satna":              {"state":"Madhya Pradesh", "lat":24.60, "lon":80.83, "display":"Satna"},
    "chhindwara":         {"state":"Madhya Pradesh", "lat":22.06, "lon":78.94, "display":"Chhindwara"},
    "hoshangabad":        {"state":"Madhya Pradesh", "lat":22.75, "lon":77.73, "display":"Hoshangabad (Narmadapuram)"},
    "vidisha":            {"state":"Madhya Pradesh", "lat":23.53, "lon":77.81, "display":"Vidisha"},
    "raisen":             {"state":"Madhya Pradesh", "lat":23.33, "lon":77.79, "display":"Raisen"},
    "damoh":              {"state":"Madhya Pradesh", "lat":23.83, "lon":79.43, "display":"Damoh"},
    "katni":              {"state":"Madhya Pradesh", "lat":23.84, "lon":80.40, "display":"Katni"},
    "shahdol":            {"state":"Madhya Pradesh", "lat":23.30, "lon":81.36, "display":"Shahdol"},
    "shivpuri":           {"state":"Madhya Pradesh", "lat":25.43, "lon":77.66, "display":"Shivpuri"},
    "morena":             {"state":"Madhya Pradesh", "lat":26.50, "lon":78.00, "display":"Morena"},
    "bhind":              {"state":"Madhya Pradesh", "lat":26.56, "lon":78.79, "display":"Bhind"},
    "datia":              {"state":"Madhya Pradesh", "lat":25.67, "lon":78.46, "display":"Datia"},
    "tikamgarh":          {"state":"Madhya Pradesh", "lat":24.74, "lon":78.83, "display":"Tikamgarh"},
    "chhatarpur":         {"state":"Madhya Pradesh", "lat":24.92, "lon":79.59, "display":"Chhatarpur"},
    "panna":              {"state":"Madhya Pradesh", "lat":24.72, "lon":80.19, "display":"Panna"},
    "mandla":             {"state":"Madhya Pradesh", "lat":22.60, "lon":80.38, "display":"Mandla"},
    "seoni":              {"state":"Madhya Pradesh", "lat":22.09, "lon":79.55, "display":"Seoni"},
    "balaghat":           {"state":"Madhya Pradesh", "lat":21.81, "lon":80.19, "display":"Balaghat"},
    "narsimhapur":        {"state":"Madhya Pradesh", "lat":22.95, "lon":79.19, "display":"Narsimhapur"},
    "betul":              {"state":"Madhya Pradesh", "lat":21.91, "lon":77.90, "display":"Betul"},
    "harda":              {"state":"Madhya Pradesh", "lat":22.34, "lon":77.09, "display":"Harda"},
    "khandwa":            {"state":"Madhya Pradesh", "lat":21.83, "lon":76.35, "display":"Khandwa (East Nimar)"},
    "khargone":           {"state":"Madhya Pradesh", "lat":21.82, "lon":75.61, "display":"Khargone (West Nimar)"},
    "barwani":            {"state":"Madhya Pradesh", "lat":22.03, "lon":74.90, "display":"Barwani"},
    "dhar":               {"state":"Madhya Pradesh", "lat":22.60, "lon":75.30, "display":"Dhar"},
    "jhabua":             {"state":"Madhya Pradesh", "lat":22.77, "lon":74.59, "display":"Jhabua"},
    "alirajpur":          {"state":"Madhya Pradesh", "lat":22.31, "lon":74.36, "display":"Alirajpur"},
    "dewas":              {"state":"Madhya Pradesh", "lat":22.97, "lon":76.05, "display":"Dewas"},
    "shajapur":           {"state":"Madhya Pradesh", "lat":23.43, "lon":76.28, "display":"Shajapur (Agar Malwa)"},
    "mandsaur":           {"state":"Madhya Pradesh", "lat":24.07, "lon":75.07, "display":"Mandsaur"},
    "neemuch":            {"state":"Madhya Pradesh", "lat":24.48, "lon":74.87, "display":"Neemuch"},
    "ratlam":             {"state":"Madhya Pradesh", "lat":23.33, "lon":75.04, "display":"Ratlam"},
    "rajgarh":            {"state":"Madhya Pradesh", "lat":24.02, "lon":76.73, "display":"Rajgarh"},
    "sehore":             {"state":"Madhya Pradesh", "lat":23.20, "lon":77.08, "display":"Sehore"},
    "guna":               {"state":"Madhya Pradesh", "lat":24.65, "lon":77.31, "display":"Guna"},
    "ashoknagar":         {"state":"Madhya Pradesh", "lat":24.58, "lon":77.73, "display":"Ashoknagar"},
    # ── MAHARASHTRA ──
    "mumbai":             {"state":"Maharashtra",    "lat":19.08, "lon":72.88, "display":"Mumbai"},
    "pune":               {"state":"Maharashtra",    "lat":18.52, "lon":73.86, "display":"Pune"},
    "nagpur":             {"state":"Maharashtra",    "lat":21.15, "lon":79.09, "display":"Nagpur"},
    "nashik":             {"state":"Maharashtra",    "lat":20.00, "lon":73.79, "display":"Nashik"},
    "thane":              {"state":"Maharashtra",    "lat":19.22, "lon":73.00, "display":"Thane"},
    "aurangabad_mh":      {"state":"Maharashtra",    "lat":19.88, "lon":75.34, "display":"Aurangabad (Chhatrapati Sambhajinagar)"},
    "solapur":            {"state":"Maharashtra",    "lat":17.69, "lon":75.91, "display":"Solapur"},
    "kolhapur":           {"state":"Maharashtra",    "lat":16.70, "lon":74.24, "display":"Kolhapur"},
    "satara":             {"state":"Maharashtra",    "lat":17.69, "lon":74.00, "display":"Satara"},
    "sangli":             {"state":"Maharashtra",    "lat":16.85, "lon":74.57, "display":"Sangli"},
    "ahmednagar":         {"state":"Maharashtra",    "lat":19.09, "lon":74.74, "display":"Ahmednagar"},
    "jalgaon":            {"state":"Maharashtra",    "lat":21.01, "lon":75.57, "display":"Jalgaon"},
    "amravati":           {"state":"Maharashtra",    "lat":20.93, "lon":77.75, "display":"Amravati"},
    "akola":              {"state":"Maharashtra",    "lat":20.70, "lon":77.00, "display":"Akola"},
    "yavatmal":           {"state":"Maharashtra",    "lat":20.40, "lon":78.12, "display":"Yavatmal"},
    "nanded":             {"state":"Maharashtra",    "lat":19.15, "lon":77.32, "display":"Nanded"},
    "latur":              {"state":"Maharashtra",    "lat":18.40, "lon":76.58, "display":"Latur"},
    "osmanabad":          {"state":"Maharashtra",    "lat":18.17, "lon":76.03, "display":"Osmanabad (Dharashiv)"},
    "beed":               {"state":"Maharashtra",    "lat":18.99, "lon":75.76, "display":"Beed"},
    "jalna":              {"state":"Maharashtra",    "lat":19.84, "lon":75.88, "display":"Jalna"},
    "parbhani":           {"state":"Maharashtra",    "lat":19.27, "lon":76.78, "display":"Parbhani"},
    "hingoli":            {"state":"Maharashtra",    "lat":19.72, "lon":77.15, "display":"Hingoli"},
    "washim":             {"state":"Maharashtra",    "lat":20.10, "lon":77.13, "display":"Washim"},
    "buldhana":           {"state":"Maharashtra",    "lat":20.53, "lon":76.18, "display":"Buldhana"},
    "wardha":             {"state":"Maharashtra",    "lat":20.75, "lon":78.60, "display":"Wardha"},
    "chandrapur":         {"state":"Maharashtra",    "lat":19.96, "lon":79.30, "display":"Chandrapur"},
    "gadchiroli":         {"state":"Maharashtra",    "lat":20.18, "lon":80.00, "display":"Gadchiroli"},
    "gondia":             {"state":"Maharashtra",    "lat":21.46, "lon":80.20, "display":"Gondia"},
    "bhandara":           {"state":"Maharashtra",    "lat":21.17, "lon":79.65, "display":"Bhandara"},
    "raigad":             {"state":"Maharashtra",    "lat":18.52, "lon":73.18, "display":"Raigad"},
    "ratnagiri":          {"state":"Maharashtra",    "lat":16.99, "lon":73.31, "display":"Ratnagiri"},
    "sindhudurg":         {"state":"Maharashtra",    "lat":16.35, "lon":73.57, "display":"Sindhudurg"},
    "dhule":              {"state":"Maharashtra",    "lat":20.90, "lon":74.78, "display":"Dhule"},
    "nandurbar":          {"state":"Maharashtra",    "lat":21.37, "lon":74.24, "display":"Nandurbar"},
    # ── MANIPUR ──
    "imphal_west":        {"state":"Manipur",        "lat":24.82, "lon":93.94, "display":"Imphal West"},
    "imphal_east":        {"state":"Manipur",        "lat":24.82, "lon":93.96, "display":"Imphal East"},
    "thoubal":            {"state":"Manipur",        "lat":24.64, "lon":93.99, "display":"Thoubal"},
    "bishnupur_mn":       {"state":"Manipur",        "lat":24.63, "lon":93.76, "display":"Bishnupur"},
    "churachandpur":      {"state":"Manipur",        "lat":24.33, "lon":93.68, "display":"Churachandpur"},
    "senapati":           {"state":"Manipur",        "lat":25.27, "lon":94.02, "display":"Senapati"},
    "ukhrul":             {"state":"Manipur",        "lat":25.10, "lon":94.37, "display":"Ukhrul"},
    "tamenglong":         {"state":"Manipur",        "lat":24.98, "lon":93.51, "display":"Tamenglong"},
    # ── MEGHALAYA ──
    "east_khasi_hills":   {"state":"Meghalaya",      "lat":25.55, "lon":91.88, "display":"East Khasi Hills (Shillong)"},
    "west_khasi_hills":   {"state":"Meghalaya",      "lat":25.47, "lon":91.27, "display":"West Khasi Hills"},
    "ri_bhoi":            {"state":"Meghalaya",      "lat":25.73, "lon":91.97, "display":"Ri Bhoi"},
    "jaintia_hills":      {"state":"Meghalaya",      "lat":25.40, "lon":92.48, "display":"Jaintia Hills"},
    "east_garo_hills":    {"state":"Meghalaya",      "lat":25.53, "lon":90.67, "display":"East Garo Hills"},
    "west_garo_hills":    {"state":"Meghalaya",      "lat":25.58, "lon":90.22, "display":"West Garo Hills"},
    # ── MIZORAM ──
    "aizawl":             {"state":"Mizoram",        "lat":23.74, "lon":92.72, "display":"Aizawl"},
    "lunglei":            {"state":"Mizoram",        "lat":22.88, "lon":92.74, "display":"Lunglei"},
    "champhai":           {"state":"Mizoram",        "lat":23.46, "lon":93.32, "display":"Champhai"},
    "serchhip":           {"state":"Mizoram",        "lat":23.30, "lon":92.85, "display":"Serchhip"},
    "kolasib":            {"state":"Mizoram",        "lat":24.22, "lon":92.68, "display":"Kolasib"},
    # ── NAGALAND ──
    "kohima":             {"state":"Nagaland",       "lat":25.67, "lon":94.12, "display":"Kohima"},
    "dimapur":            {"state":"Nagaland",       "lat":25.91, "lon":93.73, "display":"Dimapur"},
    "mokokchung":         {"state":"Nagaland",       "lat":26.33, "lon":94.52, "display":"Mokokchung"},
    "wokha":              {"state":"Nagaland",       "lat":26.10, "lon":94.27, "display":"Wokha"},
    "phek":               {"state":"Nagaland",       "lat":25.67, "lon":94.47, "display":"Phek"},
    "tuensang":           {"state":"Nagaland",       "lat":26.27, "lon":94.83, "display":"Tuensang"},
    "mon":                {"state":"Nagaland",       "lat":26.73, "lon":95.00, "display":"Mon"},
    # ── ODISHA ──
    "bhubaneswar":        {"state":"Odisha",         "lat":20.30, "lon":85.82, "display":"Khordha (Bhubaneswar)"},
    "cuttack":            {"state":"Odisha",         "lat":20.46, "lon":85.88, "display":"Cuttack"},
    "sambalpur":          {"state":"Odisha",         "lat":21.47, "lon":83.97, "display":"Sambalpur"},
    "puri":               {"state":"Odisha",         "lat":19.81, "lon":85.83, "display":"Puri"},
    "balasore":           {"state":"Odisha",         "lat":21.50, "lon":86.93, "display":"Balasore"},
    "mayurbhanj":         {"state":"Odisha",         "lat":22.04, "lon":86.52, "display":"Mayurbhanj"},
    "koraput":            {"state":"Odisha",         "lat":18.81, "lon":82.71, "display":"Koraput"},
    "sundargarh":         {"state":"Odisha",         "lat":22.12, "lon":84.02, "display":"Sundargarh"},
    "keonjhar":           {"state":"Odisha",         "lat":21.63, "lon":85.58, "display":"Keonjhar"},
    "ganjam":             {"state":"Odisha",         "lat":19.38, "lon":84.67, "display":"Ganjam"},
    "kalahandi":          {"state":"Odisha",         "lat":19.91, "lon":83.17, "display":"Kalahandi"},
    "nuapada":            {"state":"Odisha",         "lat":20.77, "lon":82.55, "display":"Nuapada"},
    "bargarh":            {"state":"Odisha",         "lat":21.34, "lon":83.62, "display":"Bargarh"},
    "jharsuguda":         {"state":"Odisha",         "lat":21.86, "lon":84.01, "display":"Jharsuguda"},
    "bolangir":           {"state":"Odisha",         "lat":20.70, "lon":83.49, "display":"Bolangir"},
    "boudh":              {"state":"Odisha",         "lat":20.84, "lon":84.32, "display":"Boudh"},
    "nayagarh":           {"state":"Odisha",         "lat":20.12, "lon":85.10, "display":"Nayagarh"},
    "kandhamal":          {"state":"Odisha",         "lat":20.47, "lon":84.24, "display":"Kandhamal"},
    # ── PUNJAB ──
    "amritsar":           {"state":"Punjab",         "lat":31.63, "lon":74.87, "display":"Amritsar"},
    "ludhiana":           {"state":"Punjab",         "lat":30.90, "lon":75.85, "display":"Ludhiana"},
    "jalandhar":          {"state":"Punjab",         "lat":31.33, "lon":75.58, "display":"Jalandhar"},
    "patiala":            {"state":"Punjab",         "lat":30.34, "lon":76.39, "display":"Patiala"},
    "bathinda":           {"state":"Punjab",         "lat":30.21, "lon":74.95, "display":"Bathinda"},
    "moga":               {"state":"Punjab",         "lat":30.82, "lon":75.17, "display":"Moga"},
    "hoshiarpur":         {"state":"Punjab",         "lat":31.53, "lon":75.91, "display":"Hoshiarpur"},
    "gurdaspur":          {"state":"Punjab",         "lat":32.04, "lon":75.40, "display":"Gurdaspur"},
    "ferozepur":          {"state":"Punjab",         "lat":30.93, "lon":74.62, "display":"Ferozepur"},
    "fazilka":            {"state":"Punjab",         "lat":30.40, "lon":74.03, "display":"Fazilka"},
    "faridkot":           {"state":"Punjab",         "lat":30.68, "lon":74.76, "display":"Faridkot"},
    "muktsar":            {"state":"Punjab",         "lat":30.47, "lon":74.52, "display":"Muktsar"},
    "sangrur":            {"state":"Punjab",         "lat":30.25, "lon":75.84, "display":"Sangrur"},
    "barnala":            {"state":"Punjab",         "lat":30.38, "lon":75.55, "display":"Barnala"},
    "ropar":              {"state":"Punjab",         "lat":30.97, "lon":76.52, "display":"Rupnagar (Ropar)"},
    "sas_nagar":          {"state":"Punjab",         "lat":30.67, "lon":76.72, "display":"SAS Nagar (Mohali)"},
    "fatehgarh_sahib":    {"state":"Punjab",         "lat":30.65, "lon":76.39, "display":"Fatehgarh Sahib"},
    "nawanshahr":         {"state":"Punjab",         "lat":31.13, "lon":76.12, "display":"Nawanshahr (Shaheed Bhagat Singh Nagar)"},
    "kapurthala":         {"state":"Punjab",         "lat":31.38, "lon":75.38, "display":"Kapurthala"},
    "tarn_taran":         {"state":"Punjab",         "lat":31.45, "lon":74.93, "display":"Tarn Taran"},
    # ── RAJASTHAN ──
    "jaipur":             {"state":"Rajasthan",      "lat":26.91, "lon":75.79, "display":"Jaipur"},
    "jodhpur":            {"state":"Rajasthan",      "lat":26.29, "lon":73.02, "display":"Jodhpur"},
    "udaipur":            {"state":"Rajasthan",      "lat":24.58, "lon":73.69, "display":"Udaipur"},
    "kota":               {"state":"Rajasthan",      "lat":25.18, "lon":75.83, "display":"Kota"},
    "ajmer":              {"state":"Rajasthan",      "lat":26.45, "lon":74.64, "display":"Ajmer"},
    "bikaner":            {"state":"Rajasthan",      "lat":28.02, "lon":73.31, "display":"Bikaner"},
    "alwar":              {"state":"Rajasthan",      "lat":27.56, "lon":76.60, "display":"Alwar"},
    "bhilwara":           {"state":"Rajasthan",      "lat":25.35, "lon":74.63, "display":"Bhilwara"},
    "sikar":              {"state":"Rajasthan",      "lat":27.61, "lon":75.15, "display":"Sikar"},
    "nagaur":             {"state":"Rajasthan",      "lat":27.20, "lon":73.74, "display":"Nagaur"},
    "pali":               {"state":"Rajasthan",      "lat":25.77, "lon":73.32, "display":"Pali"},
    "tonk":               {"state":"Rajasthan",      "lat":26.17, "lon":75.79, "display":"Tonk"},
    "dausa":              {"state":"Rajasthan",      "lat":26.89, "lon":76.33, "display":"Dausa"},
    "churu":              {"state":"Rajasthan",      "lat":28.30, "lon":74.96, "display":"Churu"},
    "jhunjhunu":          {"state":"Rajasthan",      "lat":28.13, "lon":75.40, "display":"Jhunjhunu"},
    "hanumangarh":        {"state":"Rajasthan",      "lat":29.58, "lon":74.33, "display":"Hanumangarh"},
    "ganganagar":         {"state":"Rajasthan",      "lat":29.93, "lon":73.88, "display":"Sri Ganganagar"},
    "jaisalmer":          {"state":"Rajasthan",      "lat":26.92, "lon":70.91, "display":"Jaisalmer"},
    "barmer":             {"state":"Rajasthan",      "lat":25.75, "lon":71.39, "display":"Barmer"},
    "jalore":             {"state":"Rajasthan",      "lat":25.35, "lon":72.62, "display":"Jalore"},
    "sirohi":             {"state":"Rajasthan",      "lat":24.88, "lon":72.86, "display":"Sirohi"},
    "bundi":              {"state":"Rajasthan",      "lat":25.44, "lon":75.64, "display":"Bundi"},
    "baran":              {"state":"Rajasthan",      "lat":25.10, "lon":76.52, "display":"Baran"},
    "jhalawar":           {"state":"Rajasthan",      "lat":24.60, "lon":76.15, "display":"Jhalawar"},
    "chittorgarh":        {"state":"Rajasthan",      "lat":24.89, "lon":74.62, "display":"Chittorgarh"},
    "dungarpur":          {"state":"Rajasthan",      "lat":23.84, "lon":73.71, "display":"Dungarpur"},
    "banswara":           {"state":"Rajasthan",      "lat":23.55, "lon":74.44, "display":"Banswara"},
    "pratapgarh_rj":      {"state":"Rajasthan",      "lat":24.03, "lon":74.78, "display":"Pratapgarh (Raj)"},
    "rajasamand":         {"state":"Rajasthan",      "lat":25.07, "lon":73.88, "display":"Rajsamand"},
    # ── SIKKIM ──
    "east_sikkim":        {"state":"Sikkim",         "lat":27.33, "lon":88.61, "display":"East Sikkim (Gangtok)"},
    "west_sikkim":        {"state":"Sikkim",         "lat":27.29, "lon":88.22, "display":"West Sikkim"},
    "north_sikkim":       {"state":"Sikkim",         "lat":27.73, "lon":88.43, "display":"North Sikkim"},
    "south_sikkim":       {"state":"Sikkim",         "lat":27.15, "lon":88.48, "display":"South Sikkim"},
    # ── TAMIL NADU ──
    "chennai":            {"state":"Tamil Nadu",     "lat":13.08, "lon":80.27, "display":"Chennai"},
    "coimbatore":         {"state":"Tamil Nadu",     "lat":11.02, "lon":76.97, "display":"Coimbatore"},
    "madurai":            {"state":"Tamil Nadu",     "lat":9.93,  "lon":78.12, "display":"Madurai"},
    "tiruchirappalli":    {"state":"Tamil Nadu",     "lat":10.80, "lon":78.69, "display":"Tiruchirappalli"},
    "tirunelveli":        {"state":"Tamil Nadu",     "lat":8.73,  "lon":77.70, "display":"Tirunelveli"},
    "salem":              {"state":"Tamil Nadu",     "lat":11.65, "lon":78.15, "display":"Salem"},
    "erode":              {"state":"Tamil Nadu",     "lat":11.34, "lon":77.73, "display":"Erode"},
    "tiruppur":           {"state":"Tamil Nadu",     "lat":11.11, "lon":77.34, "display":"Tiruppur"},
    "vellore":            {"state":"Tamil Nadu",     "lat":12.92, "lon":79.13, "display":"Vellore"},
    "thanjavur":          {"state":"Tamil Nadu",     "lat":10.79, "lon":79.14, "display":"Thanjavur"},
    "kanchipuram":        {"state":"Tamil Nadu",     "lat":12.83, "lon":79.70, "display":"Kanchipuram"},
    "tiruvannamalai":     {"state":"Tamil Nadu",     "lat":12.22, "lon":79.07, "display":"Tiruvannamalai"},
    "dindigul":           {"state":"Tamil Nadu",     "lat":10.37, "lon":77.97, "display":"Dindigul"},
    "cuddalore":          {"state":"Tamil Nadu",     "lat":11.75, "lon":79.77, "display":"Cuddalore"},
    "nagapattinam":       {"state":"Tamil Nadu",     "lat":10.77, "lon":79.84, "display":"Nagapattinam"},
    "villupuram":         {"state":"Tamil Nadu",     "lat":11.94, "lon":79.49, "display":"Villupuram"},
    "ramanathapuram":     {"state":"Tamil Nadu",     "lat":9.37,  "lon":78.83, "display":"Ramanathapuram"},
    "virudhunagar":       {"state":"Tamil Nadu",     "lat":9.59,  "lon":77.96, "display":"Virudhunagar"},
    "tenkasi":            {"state":"Tamil Nadu",     "lat":8.96,  "lon":77.32, "display":"Tenkasi"},
    "krishnagiri":        {"state":"Tamil Nadu",     "lat":12.52, "lon":78.21, "display":"Krishnagiri"},
    "dharmapuri":         {"state":"Tamil Nadu",     "lat":12.13, "lon":78.16, "display":"Dharmapuri"},
    "namakkal":           {"state":"Tamil Nadu",     "lat":11.22, "lon":78.17, "display":"Namakkal"},
    "karur":              {"state":"Tamil Nadu",     "lat":10.96, "lon":78.08, "display":"Karur"},
    "sivaganga":          {"state":"Tamil Nadu",     "lat":9.85,  "lon":78.48, "display":"Sivaganga"},
    "nilgiris":           {"state":"Tamil Nadu",     "lat":11.42, "lon":76.74, "display":"Nilgiris (Ooty)"},
    "theni":              {"state":"Tamil Nadu",     "lat":10.01, "lon":77.48, "display":"Theni"},
    "perambalur":         {"state":"Tamil Nadu",     "lat":11.23, "lon":78.88, "display":"Perambalur"},
    "ariyalur":           {"state":"Tamil Nadu",     "lat":11.14, "lon":79.08, "display":"Ariyalur"},
    "pudukkottai":        {"state":"Tamil Nadu",     "lat":10.38, "lon":78.82, "display":"Pudukkottai"},
    "tiruvarur":          {"state":"Tamil Nadu",     "lat":10.77, "lon":79.64, "display":"Tiruvarur"},
    "thoothukudi":        {"state":"Tamil Nadu",     "lat":8.76,  "lon":78.13, "display":"Thoothukudi (Tuticorin)"},
    "kanyakumari":        {"state":"Tamil Nadu",     "lat":8.09,  "lon":77.55, "display":"Kanyakumari"},
    # ── TELANGANA ──
    "hyderabad":          {"state":"Telangana",      "lat":17.38, "lon":78.49, "display":"Hyderabad"},
    "warangal":           {"state":"Telangana",      "lat":18.00, "lon":79.59, "display":"Warangal"},
    "nizamabad":          {"state":"Telangana",      "lat":18.67, "lon":78.10, "display":"Nizamabad"},
    "karimnagar":         {"state":"Telangana",      "lat":18.44, "lon":79.13, "display":"Karimnagar"},
    "khammam":            {"state":"Telangana",      "lat":17.25, "lon":80.15, "display":"Khammam"},
    "nalgonda":           {"state":"Telangana",      "lat":17.05, "lon":79.27, "display":"Nalgonda"},
    "medak":              {"state":"Telangana",      "lat":18.05, "lon":78.27, "display":"Medak"},
    "mahabubnagar":       {"state":"Telangana",      "lat":16.74, "lon":77.99, "display":"Mahabubnagar"},
    "adilabad":           {"state":"Telangana",      "lat":19.67, "lon":78.53, "display":"Adilabad"},
    "sangareddy":         {"state":"Telangana",      "lat":17.62, "lon":78.09, "display":"Sangareddy"},
    "rangareddy":         {"state":"Telangana",      "lat":17.37, "lon":78.49, "display":"Ranga Reddy"},
    "siddipet":           {"state":"Telangana",      "lat":18.10, "lon":78.85, "display":"Siddipet"},
    "suryapet":           {"state":"Telangana",      "lat":17.15, "lon":79.63, "display":"Suryapet"},
    "bhadradri_kothagudem":{"state":"Telangana",     "lat":17.55, "lon":80.62, "display":"Bhadradri Kothagudem"},
    "jagtial":            {"state":"Telangana",      "lat":18.79, "lon":79.00, "display":"Jagtial"},
    "mancherial":         {"state":"Telangana",      "lat":18.87, "lon":79.45, "display":"Mancherial"},
    # ── TRIPURA ──
    "west_tripura":       {"state":"Tripura",        "lat":23.83, "lon":91.28, "display":"West Tripura (Agartala)"},
    "north_tripura":      {"state":"Tripura",        "lat":24.42, "lon":92.04, "display":"North Tripura"},
    "south_tripura":      {"state":"Tripura",        "lat":23.27, "lon":91.76, "display":"South Tripura"},
    "dhalai":             {"state":"Tripura",        "lat":23.93, "lon":91.99, "display":"Dhalai"},
    # ── UTTAR PRADESH ──
    "lucknow":            {"state":"Uttar Pradesh",  "lat":26.85, "lon":80.95, "display":"Lucknow"},
    "kanpur":             {"state":"Uttar Pradesh",  "lat":26.46, "lon":80.35, "display":"Kanpur"},
    "agra":               {"state":"Uttar Pradesh",  "lat":27.18, "lon":78.01, "display":"Agra"},
    "varanasi":           {"state":"Uttar Pradesh",  "lat":25.32, "lon":82.97, "display":"Varanasi"},
    "prayagraj":          {"state":"Uttar Pradesh",  "lat":25.44, "lon":81.84, "display":"Prayagraj (Allahabad)"},
    "ghaziabad":          {"state":"Uttar Pradesh",  "lat":28.67, "lon":77.43, "display":"Ghaziabad"},
    "meerut":             {"state":"Uttar Pradesh",  "lat":29.02, "lon":77.70, "display":"Meerut"},
    "noida":              {"state":"Uttar Pradesh",  "lat":28.54, "lon":77.39, "display":"Gautam Buddha Nagar (Noida)"},
    "mathura":            {"state":"Uttar Pradesh",  "lat":27.49, "lon":77.67, "display":"Mathura"},
    "aligarh":            {"state":"Uttar Pradesh",  "lat":27.88, "lon":78.08, "display":"Aligarh"},
    "bareilly":           {"state":"Uttar Pradesh",  "lat":28.35, "lon":79.42, "display":"Bareilly"},
    "moradabad":          {"state":"Uttar Pradesh",  "lat":28.84, "lon":78.78, "display":"Moradabad"},
    "gorakhpur":          {"state":"Uttar Pradesh",  "lat":26.76, "lon":83.37, "display":"Gorakhpur"},
    "saharanpur":         {"state":"Uttar Pradesh",  "lat":29.97, "lon":77.55, "display":"Saharanpur"},
    "firozabad":          {"state":"Uttar Pradesh",  "lat":27.15, "lon":78.40, "display":"Firozabad"},
    "jhansi":             {"state":"Uttar Pradesh",  "lat":25.45, "lon":78.57, "display":"Jhansi"},
    "muzaffarnagar":      {"state":"Uttar Pradesh",  "lat":29.47, "lon":77.70, "display":"Muzaffarnagar"},
    "rampur":             {"state":"Uttar Pradesh",  "lat":28.80, "lon":79.03, "display":"Rampur"},
    "etawah":             {"state":"Uttar Pradesh",  "lat":26.78, "lon":79.02, "display":"Etawah"},
    "mainpuri":           {"state":"Uttar Pradesh",  "lat":27.23, "lon":79.02, "display":"Mainpuri"},
    "bulandshahr":        {"state":"Uttar Pradesh",  "lat":28.41, "lon":77.85, "display":"Bulandshahr"},
    "shahjahanpur":       {"state":"Uttar Pradesh",  "lat":27.88, "lon":79.90, "display":"Shahjahanpur"},
    "sitapur":            {"state":"Uttar Pradesh",  "lat":27.57, "lon":80.68, "display":"Sitapur"},
    "hardoi":             {"state":"Uttar Pradesh",  "lat":27.40, "lon":80.13, "display":"Hardoi"},
    "unnao":              {"state":"Uttar Pradesh",  "lat":26.55, "lon":80.49, "display":"Unnao"},
    "rae_bareli":         {"state":"Uttar Pradesh",  "lat":26.23, "lon":81.24, "display":"Rae Bareli"},
    "lakhimpur_kheri":    {"state":"Uttar Pradesh",  "lat":27.95, "lon":80.78, "display":"Lakhimpur Kheri"},
    "bahraich":           {"state":"Uttar Pradesh",  "lat":27.57, "lon":81.60, "display":"Bahraich"},
    "balrampur":          {"state":"Uttar Pradesh",  "lat":27.43, "lon":82.18, "display":"Balrampur"},
    "gonda":              {"state":"Uttar Pradesh",  "lat":27.13, "lon":81.96, "display":"Gonda"},
    "basti":              {"state":"Uttar Pradesh",  "lat":26.80, "lon":82.73, "display":"Basti"},
    "sant_kabir_nagar":   {"state":"Uttar Pradesh",  "lat":26.79, "lon":83.08, "display":"Sant Kabir Nagar"},
    "maharajganj":        {"state":"Uttar Pradesh",  "lat":27.13, "lon":83.59, "display":"Maharajganj"},
    "deoria":             {"state":"Uttar Pradesh",  "lat":26.50, "lon":83.78, "display":"Deoria"},
    "kushinagar":         {"state":"Uttar Pradesh",  "lat":26.74, "lon":83.79, "display":"Kushinagar"},
    "azamgarh":           {"state":"Uttar Pradesh",  "lat":26.07, "lon":83.19, "display":"Azamgarh"},
    "mau":                {"state":"Uttar Pradesh",  "lat":25.94, "lon":83.56, "display":"Mau"},
    "ballia":             {"state":"Uttar Pradesh",  "lat":25.76, "lon":84.15, "display":"Ballia"},
    "ghazipur":           {"state":"Uttar Pradesh",  "lat":25.58, "lon":83.57, "display":"Ghazipur"},
    "mirzapur":           {"state":"Uttar Pradesh",  "lat":25.15, "lon":82.57, "display":"Mirzapur"},
    "sonbhadra":          {"state":"Uttar Pradesh",  "lat":24.68, "lon":83.07, "display":"Sonbhadra"},
    "allahabad":          {"state":"Uttar Pradesh",  "lat":25.44, "lon":81.84, "display":"Allahabad"},
    "fatehpur":           {"state":"Uttar Pradesh",  "lat":25.93, "lon":80.81, "display":"Fatehpur"},
    "pratapgarh_up":      {"state":"Uttar Pradesh",  "lat":25.90, "lon":81.98, "display":"Pratapgarh (UP)"},
    "kaushambi":          {"state":"Uttar Pradesh",  "lat":25.55, "lon":81.38, "display":"Kaushambi"},
    "banda":              {"state":"Uttar Pradesh",  "lat":25.47, "lon":80.34, "display":"Banda"},
    "chitrakoot":         {"state":"Uttar Pradesh",  "lat":25.20, "lon":80.89, "display":"Chitrakoot"},
    "hamirpur_up":        {"state":"Uttar Pradesh",  "lat":25.95, "lon":80.15, "display":"Hamirpur (UP)"},
    "mahoba":             {"state":"Uttar Pradesh",  "lat":25.30, "lon":79.87, "display":"Mahoba"},
    "lalitpur":           {"state":"Uttar Pradesh",  "lat":24.68, "lon":78.41, "display":"Lalitpur"},
    "etah":               {"state":"Uttar Pradesh",  "lat":27.63, "lon":78.67, "display":"Etah"},
    "kannauj":            {"state":"Uttar Pradesh",  "lat":27.06, "lon":79.92, "display":"Kannauj"},
    "auraiya":            {"state":"Uttar Pradesh",  "lat":26.46, "lon":79.51, "display":"Auraiya"},
    "kanpur_dehat":       {"state":"Uttar Pradesh",  "lat":26.42, "lon":79.83, "display":"Kanpur Dehat"},
    # ── UTTARAKHAND ──
    "dehradun":           {"state":"Uttarakhand",    "lat":30.32, "lon":78.03, "display":"Dehradun"},
    "haridwar":           {"state":"Uttarakhand",    "lat":29.95, "lon":78.16, "display":"Haridwar"},
    "nainital":           {"state":"Uttarakhand",    "lat":29.38, "lon":79.46, "display":"Nainital"},
    "almora":             {"state":"Uttarakhand",    "lat":29.60, "lon":79.66, "display":"Almora"},
    "udham_singh_nagar":  {"state":"Uttarakhand",    "lat":28.94, "lon":79.51, "display":"Udham Singh Nagar"},
    "pauri_garhwal":      {"state":"Uttarakhand",    "lat":30.15, "lon":79.47, "display":"Pauri Garhwal"},
    "tehri_garhwal":      {"state":"Uttarakhand",    "lat":30.48, "lon":78.43, "display":"Tehri Garhwal"},
    "uttarkashi":         {"state":"Uttarakhand",    "lat":30.73, "lon":78.45, "display":"Uttarkashi"},
    "chamoli":            {"state":"Uttarakhand",    "lat":30.40, "lon":79.32, "display":"Chamoli"},
    "rudraprayag":        {"state":"Uttarakhand",    "lat":30.28, "lon":78.98, "display":"Rudraprayag"},
    "pithoragarh":        {"state":"Uttarakhand",    "lat":29.58, "lon":80.21, "display":"Pithoragarh"},
    "champawat":          {"state":"Uttarakhand",    "lat":29.33, "lon":80.09, "display":"Champawat"},
    "bageshwar":          {"state":"Uttarakhand",    "lat":29.84, "lon":79.77, "display":"Bageshwar"},
    # ── WEST BENGAL ──
    "kolkata":            {"state":"West Bengal",    "lat":22.57, "lon":88.36, "display":"Kolkata"},
    "north_24_parganas":  {"state":"West Bengal",    "lat":22.85, "lon":88.51, "display":"North 24 Parganas"},
    "south_24_parganas":  {"state":"West Bengal",    "lat":22.15, "lon":88.53, "display":"South 24 Parganas"},
    "howrah":             {"state":"West Bengal",    "lat":22.59, "lon":88.26, "display":"Howrah"},
    "hooghly":            {"state":"West Bengal",    "lat":22.90, "lon":88.39, "display":"Hooghly"},
    "bardhaman":          {"state":"West Bengal",    "lat":23.25, "lon":87.86, "display":"Bardhaman"},
    "nadia":              {"state":"West Bengal",    "lat":23.47, "lon":88.55, "display":"Nadia"},
    "murshidabad":        {"state":"West Bengal",    "lat":24.18, "lon":88.27, "display":"Murshidabad"},
    "malda":              {"state":"West Bengal",    "lat":25.01, "lon":88.14, "display":"Malda"},
    "north_dinajpur":     {"state":"West Bengal",    "lat":26.08, "lon":88.25, "display":"North Dinajpur"},
    "south_dinajpur":     {"state":"West Bengal",    "lat":25.57, "lon":88.73, "display":"South Dinajpur"},
    "darjeeling":         {"state":"West Bengal",    "lat":27.04, "lon":88.26, "display":"Darjeeling"},
    "jalpaiguri":         {"state":"West Bengal",    "lat":26.54, "lon":88.73, "display":"Jalpaiguri"},
    "cooch_behar":        {"state":"West Bengal",    "lat":26.34, "lon":89.44, "display":"Cooch Behar"},
    "alipurduar":         {"state":"West Bengal",    "lat":26.48, "lon":89.53, "display":"Alipurduar"},
    "bankura":            {"state":"West Bengal",    "lat":23.23, "lon":87.07, "display":"Bankura"},
    "purulia":            {"state":"West Bengal",    "lat":23.33, "lon":86.36, "display":"Purulia"},
    "birbhum":            {"state":"West Bengal",    "lat":23.90, "lon":87.53, "display":"Birbhum"},
    "paschim_medinipur":  {"state":"West Bengal",    "lat":22.43, "lon":87.32, "display":"Paschim Medinipur"},
    "purba_medinipur":    {"state":"West Bengal",    "lat":22.43, "lon":87.74, "display":"Purba Medinipur"},
    # ── UTs ──
    "new_delhi":          {"state":"Delhi",          "lat":28.63, "lon":77.22, "display":"New Delhi"},
    "east_delhi":         {"state":"Delhi",          "lat":28.66, "lon":77.30, "display":"East Delhi"},
    "north_delhi":        {"state":"Delhi",          "lat":28.74, "lon":77.20, "display":"North Delhi"},
    "south_delhi":        {"state":"Delhi",          "lat":28.50, "lon":77.22, "display":"South Delhi"},
    "west_delhi":         {"state":"Delhi",          "lat":28.65, "lon":77.09, "display":"West Delhi"},
    "chandigarh":         {"state":"Chandigarh (UT)","lat":30.73, "lon":76.78, "display":"Chandigarh"},
    "puducherry":         {"state":"Puducherry",     "lat":11.93, "lon":79.83, "display":"Puducherry"},
    "port_blair":         {"state":"Andaman & Nicobar","lat":11.67,"lon":92.74, "display":"Port Blair (A&N Islands)"},
    "kavaratti":          {"state":"Lakshadweep",    "lat":10.56, "lon":72.64, "display":"Kavaratti (Lakshadweep)"},
    "silvassa":           {"state":"Dadra & NH",     "lat":20.27, "lon":73.01, "display":"Silvassa (DNH & DD)"},
    "daman":              {"state":"Daman & Diu",    "lat":20.41, "lon":72.84, "display":"Daman"},
    "jammu":              {"state":"Jammu & Kashmir","lat":32.73, "lon":74.87, "display":"Jammu"},
    "srinagar":           {"state":"Jammu & Kashmir","lat":34.08, "lon":74.80, "display":"Srinagar"},
    "anantnag":           {"state":"Jammu & Kashmir","lat":33.73, "lon":75.15, "display":"Anantnag"},
    "baramulla":          {"state":"Jammu & Kashmir","lat":34.20, "lon":74.34, "display":"Baramulla"},
    "leh":                {"state":"Ladakh",         "lat":34.17, "lon":77.58, "display":"Leh"},
    "kargil":             {"state":"Ladakh",         "lat":34.56, "lon":76.13, "display":"Kargil"},
}

# ── BORDEAUX MIXTURE PREPARATION GUIDE ─────────────────────────────
BM_PREPARATION = {
    "title": "Bordeaux Mixture Preparation Guide",
    "expert": EXPERT,
    "steps": [
        {"step": 1, "title": "Dissolve Copper Sulphate",
         "detail": "Dissolve 1 kg CuSO₄ in 50 litres of water in a plastic/wooden container. Never use iron/metal. Stir until fully dissolved (bright blue solution)."},
        {"step": 2, "title": "Slake Lime",
         "detail": "In a separate container, slake 1 kg freshly burnt lime in 50 litres of water. Cool completely. Freshly slaked lime gives better results than hydrated lime."},
        {"step": 3, "title": "Mix Carefully",
         "detail": "Pour the copper sulphate solution INTO the lime slurry slowly, stirring constantly. NEVER reverse this — always copper into lime, never lime into copper."},
        {"step": 4, "title": "Test pH",
         "detail": "Test with pH paper — should be 6.5–7.5 (neutral to slightly alkaline). If acidic (<6), add more lime. This pH ensures good sticking and no phytotoxicity."},
        {"step": 5, "title": "Spray Immediately",
         "detail": "Use within 4 hours of preparation. Bordeaux mixture degrades rapidly. Never store — always freshly prepared before spraying."},
    ],
    "chemistry_note": (
        "CuSO₄ is the active fungicide. Ca(OH)₂ neutralises acidity and reacts with CO₂ in air to "
        "form CaCO₃ — a rainfast calcium-copper coating. This CO₂ reaction needs 24 hours to complete, "
        "which is why Bordeaux spray requires a 24-hour rain-free window post-application."
    ),
}
